version: '3'
services:
  c:
    hostname: collect
    container_name: collect-service
    build: ./collect
    depends_on:
      - s
    ports:
      - 9001:9001
    volumes:
      - .:/usr/src/application
    environment:
      - ENV=development
      - HOST=0.0.0.0
      - PORT=9001
    networks:
      - tiered
  s:
    hostname: store
    container_name: store-service
    build: ./store
    depends_on:
      - mongodb
    ports:
      - 8002:8002
    volumes:
      - .:/usr/src/application
    environment:
      - ENV=development
      - HOST=0.0.0.0
      - PORT=8002
      - DB=mongodb://mongodb:27017/dgoc
    networks:
      - tiered
  q:
    hostname: queue
    container_name: queue-service
    build: ./queue
    depends_on:
      - s
    ports:
      - 8003:8003
    volumes:
      - .:/usr/src/application
    environment:
      - ENV=development
      - HOST=0.0.0.0
      - PORT=8003
    networks:
      - tiered
  mongodb:
    hostname: database
    container_name: mongo-database
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/usr/data/db
    command: mongod #--smallfiles --logpath=/dev/null
    networks:
      - tiered
networks:
  tiered: